<?php

// This file was generated by running "composer dump-env prod"

return array (
  'APP_ENV' => 'prod',
  'SYMFONY_DOTENV_PATH' => './.env',
  'APP_SECRET' => 'a48dc775a7eae3a20cf02dfa416918fe',
  'DATABASE_URL' => 'mysql://naby:Toure77%40!@127.0.0.1:3306/adminitoure?serverVersion=8.0.42&charset=utf8mb4',
  'MESSENGER_TRANSPORT_DSN' => 'doctrine://default?auto_setup=0',
  'MAILER_DSN' => 'smtp://nabytoure-admin@nabytoure.com:Toure77@@smtp.hostinger.com:465',
  'JWT_SECRET' => '0hLaLaTourenaby13207e!',
);
